-- CreateTable
CREATE TABLE "AgentWorkLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "projectAgentId" TEXT NOT NULL,
    "taskId" TEXT,
    "date" TEXT NOT NULL,
    "hours" REAL NOT NULL,
    "description" TEXT,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "AgentWorkLog_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "AgentWorkLog_projectAgentId_fkey" FOREIGN KEY ("projectAgentId") REFERENCES "ProjectAgent" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ProjectDoc" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "docType" TEXT NOT NULL DEFAULT 'general',
    "status" TEXT NOT NULL DEFAULT 'draft',
    "parentDocId" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "linkedTaskIds" TEXT,
    "linkedReqIds" TEXT,
    "tags" TEXT,
    "createdBy" TEXT,
    "updatedBy" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ProjectDoc_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ProjectDoc_parentDocId_fkey" FOREIGN KEY ("parentDocId") REFERENCES "ProjectDoc" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ProjectDocVersion" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "docId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "changeLog" TEXT,
    "createdBy" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ProjectDocVersion_docId_fkey" FOREIGN KEY ("docId") REFERENCES "ProjectDoc" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ProjectTemplate" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "category" TEXT NOT NULL DEFAULT 'custom',
    "icon" TEXT,
    "isBuiltIn" BOOLEAN NOT NULL DEFAULT false,
    "isPublic" BOOLEAN NOT NULL DEFAULT false,
    "createdBy" TEXT,
    "config" TEXT NOT NULL,
    "usageCount" INTEGER NOT NULL DEFAULT 0,
    "rating" REAL,
    "tags" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateIndex
CREATE INDEX "AgentWorkLog_projectId_idx" ON "AgentWorkLog"("projectId");

-- CreateIndex
CREATE INDEX "AgentWorkLog_projectAgentId_idx" ON "AgentWorkLog"("projectAgentId");

-- CreateIndex
CREATE INDEX "AgentWorkLog_taskId_idx" ON "AgentWorkLog"("taskId");

-- CreateIndex
CREATE INDEX "AgentWorkLog_date_idx" ON "AgentWorkLog"("date");

-- CreateIndex
CREATE INDEX "AgentWorkLog_projectId_date_idx" ON "AgentWorkLog"("projectId", "date");

-- CreateIndex
CREATE INDEX "ProjectDoc_projectId_idx" ON "ProjectDoc"("projectId");

-- CreateIndex
CREATE INDEX "ProjectDoc_docType_idx" ON "ProjectDoc"("docType");

-- CreateIndex
CREATE INDEX "ProjectDoc_status_idx" ON "ProjectDoc"("status");

-- CreateIndex
CREATE INDEX "ProjectDoc_parentDocId_idx" ON "ProjectDoc"("parentDocId");

-- CreateIndex
CREATE INDEX "ProjectDoc_projectId_sortOrder_idx" ON "ProjectDoc"("projectId", "sortOrder");

-- CreateIndex
CREATE INDEX "ProjectDoc_createdAt_idx" ON "ProjectDoc"("createdAt");

-- CreateIndex
CREATE INDEX "ProjectDocVersion_docId_idx" ON "ProjectDocVersion"("docId");

-- CreateIndex
CREATE INDEX "ProjectDocVersion_createdAt_idx" ON "ProjectDocVersion"("createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "ProjectDocVersion_docId_version_key" ON "ProjectDocVersion"("docId", "version");

-- CreateIndex
CREATE INDEX "ProjectTemplate_category_idx" ON "ProjectTemplate"("category");

-- CreateIndex
CREATE INDEX "ProjectTemplate_isBuiltIn_idx" ON "ProjectTemplate"("isBuiltIn");

-- CreateIndex
CREATE INDEX "ProjectTemplate_isPublic_idx" ON "ProjectTemplate"("isPublic");

-- CreateIndex
CREATE INDEX "ProjectTemplate_createdBy_idx" ON "ProjectTemplate"("createdBy");

-- CreateIndex
CREATE INDEX "ProjectTemplate_usageCount_idx" ON "ProjectTemplate"("usageCount");
