// ============================================================
// Team Management Page - /project-hub/[id]/team
// ============================================================
//
// Project agent management with workload board and work logs.
// ============================================================

'use client';

import { useState, useEffect, useCallback } from 'react';
import { useParams } from 'next/navigation';
import { trpc } from '@/lib/trpc/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Bot,
  Plus,
  Clock,
  BarChart3,
  FileText,
  RefreshCw,
  UserPlus,
} from 'lucide-react';

// ---- Types ----

interface AgentItem {
  id: string;
  agentId: string;
  name: string;
  clientType: string;
  role: string;
  status: string;
  taskCount: number;
}

interface WorkloadItem {
  agentId: string;
  agentName: string;
  totalHours: number;
  taskCount: number;
  recentLogs: number;
}

interface WorkLogItem {
  id: string;
  projectAgentId: string;
  agentName: string;
  date: string;
  hours: number;
  description: string;
  autoGenerated: boolean;
}

// ---- Component ----

export default function TeamManagementPage() {
  const params = useParams();
  const projectId = params.id as string;

  const [agents, setAgents] = useState<AgentItem[]>([]);
  const [workload, setWorkload] = useState<WorkloadItem[]>([]);
  const [workLogs, setWorkLogs] = useState<WorkLogItem[]>([]);
  const [agentsLoading, setAgentsLoading] = useState(true);
  const [workloadLoading, setWorkloadLoading] = useState(true);
  const [logsLoading, setLogsLoading] = useState(true);

  const fetchAgents = useCallback(async () => {
    try {
      setAgentsLoading(true);
      const data = await trpc.projectHub.agents.list.query({ projectId });
      setAgents(data as unknown as AgentItem[]);
    } catch (err) {
      console.error('Failed to fetch agents:', err);
    } finally {
      setAgentsLoading(false);
    }
  }, [projectId]);

  const fetchWorkload = useCallback(async () => {
    try {
      setWorkloadLoading(true);
      const data = await trpc.projectHub.workLogs.workloadBoard.query({ projectId });
      setWorkload(data as unknown as WorkloadItem[]);
    } catch (err) {
      console.error('Failed to fetch workload:', err);
    } finally {
      setWorkloadLoading(false);
    }
  }, [projectId]);

  const fetchWorkLogs = useCallback(async () => {
    try {
      setLogsLoading(true);
      const data = await trpc.projectHub.workLogs.list.query({ projectId });
      setWorkLogs((data as any)?.items ?? []);
    } catch (err) {
      console.error('Failed to fetch work logs:', err);
    } finally {
      setLogsLoading(false);
    }
  }, [projectId]);

  const fetchAll = useCallback(async () => {
    await Promise.allSettled([fetchAgents(), fetchWorkload(), fetchWorkLogs()]);
  }, [fetchAgents, fetchWorkload, fetchWorkLogs]);

  useEffect(() => {
    fetchAll();
  }, [fetchAll]);

  const agentsList = agents;
  const workloadList = workload;
  const workLogsList = workLogs;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">智能体管理</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-0.5">
            管理项目智能体、查看工作负载和日志
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={() => fetchAll()}>
            <RefreshCw className="w-3.5 h-3.5 mr-1.5" />
            刷新
          </Button>
          <Button size="sm">
            <UserPlus className="w-3.5 h-3.5 mr-1.5" />
            分配智能体
          </Button>
        </div>
      </div>

      {/* Agent Table */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Bot className="w-4 h-4 text-blue-500" />
            项目智能体
          </CardTitle>
        </CardHeader>
        <CardContent>
          {agentsLoading ? (
            <div className="space-y-2">
              {Array.from({ length: 3 }).map((_, i) => (
                <div key={i} className="animate-pulse h-12 bg-gray-100 dark:bg-gray-800 rounded" />
              ))}
            </div>
          ) : agentsList.length === 0 ? (
            <p className="text-sm text-gray-400 py-8 text-center">暂无关联智能体，点击"分配智能体"开始</p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>名称</TableHead>
                  <TableHead>客户端类型</TableHead>
                  <TableHead>角色</TableHead>
                  <TableHead>状态</TableHead>
                  <TableHead className="text-right">任务数</TableHead>
                  <TableHead className="text-right">操作</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {agentsList.map((agent) => (
                  <TableRow key={agent.id}>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <div className="w-8 h-8 rounded-lg bg-blue-100 dark:bg-blue-950 flex items-center justify-center">
                          <Bot className="w-4 h-4 text-blue-600 dark:text-blue-400" />
                        </div>
                        <span className="font-medium text-gray-900 dark:text-gray-100">{agent.name}</span>
                      </div>
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline">{agent.clientType}</Badge>
                    </TableCell>
                    <TableCell>
                      <span className="text-sm text-gray-600 dark:text-gray-300">{agent.role}</span>
                    </TableCell>
                    <TableCell>
                      <Badge
                        variant={agent.status === 'active' ? 'default' : 'outline'}
                        className={agent.status === 'active' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : ''}
                      >
                        {agent.status === 'active' ? '活跃' : '离线'}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">{agent.taskCount}</TableCell>
                    <TableCell className="text-right">
                      <Button variant="ghost" size="sm">详情</Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Workload Board */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <BarChart3 className="w-4 h-4 text-violet-500" />
            工作负载看板
          </CardTitle>
        </CardHeader>
        <CardContent>
          {workloadLoading ? (
            <div className="animate-pulse h-32 bg-gray-100 dark:bg-gray-800 rounded" />
          ) : workloadList.length === 0 ? (
            <p className="text-sm text-gray-400 py-4 text-center">暂无工作负载数据</p>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {workloadList.map((item) => (
                <div
                  key={item.agentId}
                  className="p-4 rounded-lg border border-gray-200 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors"
                >
                  <div className="flex items-center gap-2 mb-3">
                    <div className="w-8 h-8 rounded-lg bg-violet-100 dark:bg-violet-950 flex items-center justify-center">
                      <Bot className="w-4 h-4 text-violet-600 dark:text-violet-400" />
                    </div>
                    <span className="font-medium text-sm text-gray-900 dark:text-gray-100">{item.agentName}</span>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <p className="text-xs text-gray-400">总工时</p>
                      <p className="text-lg font-bold text-gray-900 dark:text-gray-100">{item.totalHours}h</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-400">任务数</p>
                      <p className="text-lg font-bold text-gray-900 dark:text-gray-100">{item.taskCount}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Work Log List */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-4 h-4 text-amber-500" />
            工作日志
          </CardTitle>
        </CardHeader>
        <CardContent>
          {logsLoading ? (
            <div className="space-y-2">
              {Array.from({ length: 3 }).map((_, i) => (
                <div key={i} className="animate-pulse h-16 bg-gray-100 dark:bg-gray-800 rounded" />
              ))}
            </div>
          ) : workLogsList.length === 0 ? (
            <p className="text-sm text-gray-400 py-4 text-center">暂无工作日志</p>
          ) : (
            <div className="space-y-3">
              {workLogsList.map((log) => (
                <div
                  key={log.id}
                  className="flex items-center justify-between py-3 px-4 rounded-lg border border-gray-200 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-amber-100 dark:bg-amber-950 flex items-center justify-center">
                      <Clock className="w-4 h-4 text-amber-600 dark:text-amber-400" />
                    </div>
                    <div>
                      <p className="text-sm font-medium text-gray-900 dark:text-gray-100">{log.agentName}</p>
                      <p className="text-xs text-gray-400">{log.description || '无描述'}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3 shrink-0">
                    <span className="text-sm font-medium text-gray-700 dark:text-gray-300">{log.hours}h</span>
                    <span className="text-xs text-gray-400">{log.date}</span>
                    {log.autoGenerated && (
                      <Badge variant="outline" className="text-[10px]">自动</Badge>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
