// ============================================================
// Agent Workstation Page - /project-hub/[id]/team
// ============================================================
//
// Single agent workstation per project.
// v5.1.0: Redesigned from team management to agent workstation.
// Each project has ONE agent that does all the work.
// ============================================================

'use client';

import { useState, useEffect, useCallback } from 'react';
import { useParams } from 'next/navigation';
import { trpc } from '@/lib/trpc/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Bot,
  Clock,
  FileText,
  UserPlus,
  X,
  Play,
  Zap,
  Code,
  Brain,
  Wrench,
  MessageSquare,
} from 'lucide-react';

// ---- Types ----

interface AgentData {
  id: string;
  agentId: string;
  name: string;
  clientType: string;
  role: string;
  status: string;
  isActive: boolean;
  agent?: {
    id: string;
    name: string;
    clientType: string;
    capabilities?: string | null;
  };
}

interface WorkLogItem {
  id: string;
  projectAgentId: string;
  agentName: string;
  date: string;
  hours: number;
  description: string;
  autoGenerated: boolean;
}

// ---- Capability tags ----

const CAPABILITY_ICONS: Record<string, any> = {
  coding: Code,
  analysis: Brain,
  communication: MessageSquare,
  tools: Wrench,
};

const DEFAULT_CAPABILITIES = [
  { label: '代码编写', key: 'coding' },
  { label: '需求分析', key: 'analysis' },
  { label: '文档生成', key: 'communication' },
  { label: '工具调用', key: 'tools' },
];

// ---- Component ----

export default function AgentWorkstationPage() {
  const params = useParams();
  const projectId = params?.id as string;

  const [agent, setAgent] = useState<AgentData | null>(null);
  const [workLogs, setWorkLogs] = useState<WorkLogItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [showAssignForm, setShowAssignForm] = useState(false);

  // Assign form state
  const [newAgentName, setNewAgentName] = useState('');
  const [newAgentRole, setNewAgentRole] = useState<'lead' | 'developer' | 'reviewer' | 'observer'>('developer');
  const [newAgentClientType, setNewAgentClientType] = useState('mcp');
  const [creating, setCreating] = useState(false);

  const fetchAgent = useCallback(async () => {
    try {
      const data = await trpc.projectHub.agents.getProjectAgent.query({ projectId });
      setAgent(data as unknown as AgentData || null);
    } catch (err) {
      console.error('Failed to fetch project agent:', err);
      setAgent(null);
    }
  }, [projectId]);

  const fetchWorkLogs = useCallback(async () => {
    try {
      const data = await trpc.projectHub.workLogs.list.query({ projectId });
      setWorkLogs((data as any)?.items ?? []);
    } catch (err) {
      console.error('Failed to fetch work logs:', err);
    }
  }, [projectId]);

  const fetchAll = useCallback(async () => {
    setLoading(true);
    await Promise.allSettled([fetchAgent(), fetchWorkLogs()]);
    setLoading(false);
  }, [fetchAgent, fetchWorkLogs]);

  useEffect(() => {
    fetchAll();
  }, [fetchAll]);

  const handleAssignAgent = async () => {
    if (!newAgentName.trim()) return;
    try {
      setCreating(true);
      await trpc.projectHub.agents.createAndAssign.mutate({
        projectId,
        name: newAgentName.trim(),
        role: newAgentRole,
        clientType: newAgentClientType,
      });
      setNewAgentName('');
      setNewAgentRole('developer');
      setNewAgentClientType('mcp');
      setShowAssignForm(false);
      await fetchAll();
    } catch (err) {
      console.error('Failed to assign agent:', err);
    } finally {
      setCreating(false);
    }
  };

  const totalHours = workLogs.reduce((sum, log) => sum + (log.hours || 0), 0);

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">智能体工作台</h1>
          <p className="text-gray-500 dark:text-gray-400 text-sm mt-1">项目专属智能体的工作状态与时间线</p>
        </div>
      </div>

      {/* Loading State */}
      {loading ? (
        <div className="animate-pulse space-y-4">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-32 bg-gray-100 dark:bg-gray-800 rounded-lg" />
          ))}
        </div>
      ) : !agent ? (
        /* No agent assigned yet */
        <Card>
          <CardContent className="py-12 text-center">
            <Bot className="w-16 h-16 text-gray-300 dark:text-gray-600 mx-auto mb-4" />
            <h3 className="text-lg font-medium text-gray-600 dark:text-gray-400">尚未分配智能体</h3>
            <p className="text-sm text-gray-400 mt-1">为这个项目分配一个专属智能体来开始工作</p>
            {!showAssignForm ? (
              <Button className="mt-4" onClick={() => setShowAssignForm(true)}>
                <UserPlus className="w-4 h-4 mr-2" />
                分配智能体
              </Button>
            ) : (
              <div className="mt-6 max-w-md mx-auto space-y-3 text-left">
                <div className="flex items-center gap-2 mb-4">
                  <UserPlus className="w-4 h-4 text-blue-500" />
                  <span className="text-sm font-medium text-gray-900 dark:text-gray-100">分配专属智能体</span>
                </div>
                <div>
                  <label className="block text-xs text-gray-500 mb-1">名称</label>
                  <input
                    type="text"
                    value={newAgentName}
                    onChange={(e) => setNewAgentName(e.target.value)}
                    placeholder="输入智能体名称"
                    className="w-full px-3 py-1.5 text-sm border border-gray-300 dark:border-gray-700 rounded-md bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    onKeyDown={(e) => e.key === 'Enter' && handleAssignAgent()}
                  />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs text-gray-500 mb-1">角色</label>
                    <select
                      value={newAgentRole}
                      onChange={(e) => setNewAgentRole(e.target.value as typeof newAgentRole)}
                      className="w-full px-3 py-1.5 text-sm border border-gray-300 dark:border-gray-700 rounded-md bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    >
                      <option value="lead">Lead (负责人)</option>
                      <option value="developer">Developer (开发者)</option>
                      <option value="reviewer">Reviewer (审查者)</option>
                      <option value="observer">Observer (观察者)</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs text-gray-500 mb-1">类型</label>
                    <select
                      value={newAgentClientType}
                      onChange={(e) => setNewAgentClientType(e.target.value)}
                      className="w-full px-3 py-1.5 text-sm border border-gray-300 dark:border-gray-700 rounded-md bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    >
                      <option value="mcp">MCP</option>
                      <option value="trae">Trae</option>
                      <option value="cursor">Cursor</option>
                      <option value="claude">Claude</option>
                      <option value="chatgpt">ChatGPT</option>
                      <option value="api">API</option>
                    </select>
                  </div>
                </div>
                <div className="flex gap-2 pt-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setShowAssignForm(false)}
                  >
                    <X className="w-3 h-3 mr-1" />
                    取消
                  </Button>
                  <Button
                    size="sm"
                    onClick={handleAssignAgent}
                    disabled={!newAgentName.trim() || creating}
                  >
                    {creating ? '分配中...' : '确认分配'}
                  </Button>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      ) : (
        /* Agent Workstation */
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Left: Agent Profile Card */}
          <Card>
            <CardContent className="pt-6">
              {/* Agent Avatar & Name */}
              <div className="flex items-center gap-4 mb-4">
                <div className="w-12 h-12 rounded-full bg-indigo-100 dark:bg-indigo-900 flex items-center justify-center">
                  <Bot className="w-6 h-6 text-indigo-600 dark:text-indigo-400" />
                </div>
                <div>
                  <h3 className="font-semibold text-gray-900 dark:text-gray-100">
                    {agent.agent?.name || agent.name}
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {agent.role} &middot; {agent.agent?.clientType || agent.clientType}
                  </p>
                </div>
              </div>

              {/* Status Indicator */}
              <div className="flex items-center gap-2 mb-5 px-3 py-2 rounded-lg bg-gray-50 dark:bg-gray-800/50">
                <div className={`w-2.5 h-2.5 rounded-full ${
                  agent.isActive
                    ? 'bg-emerald-500 animate-pulse'
                    : 'bg-gray-400 dark:bg-gray-600'
                }`} />
                <span className={`text-sm font-medium ${
                  agent.isActive
                    ? 'text-emerald-600 dark:text-emerald-400'
                    : 'text-gray-500 dark:text-gray-400'
                }`}>
                  {agent.isActive ? '工作中' : '空闲'}
                </span>
              </div>

              {/* Stats */}
              <div className="space-y-3 mb-6">
                <div className="flex justify-between text-sm">
                  <span className="text-gray-500 dark:text-gray-400">累计工时</span>
                  <span className="font-medium text-gray-900 dark:text-gray-100">{totalHours}h</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-500 dark:text-gray-400">工作记录</span>
                  <span className="font-medium text-gray-900 dark:text-gray-100">{workLogs.length} 条</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-500 dark:text-gray-400">角色</span>
                  <span className="font-medium text-gray-900 dark:text-gray-100">
                    {agent.role === 'lead' ? '负责人' :
                     agent.role === 'developer' ? '开发者' :
                     agent.role === 'reviewer' ? '审查者' : '观察者'}
                  </span>
                </div>
              </div>

              {/* Capabilities */}
              <div className="mb-6">
                <p className="text-xs text-gray-500 dark:text-gray-400 mb-2 font-medium uppercase tracking-wider">能力标签</p>
                <div className="flex flex-wrap gap-1.5">
                  {DEFAULT_CAPABILITIES.map((cap) => {
                    const Icon = CAPABILITY_ICONS[cap.key] || Zap;
                    return (
                      <Badge
                        key={cap.key}
                        variant="secondary"
                        className="text-[11px] px-2 py-0.5 gap-1 bg-indigo-50 text-indigo-600 dark:bg-indigo-950 dark:text-indigo-300"
                      >
                        <Icon className="w-3 h-3" />
                        {cap.label}
                      </Badge>
                    );
                  })}
                </div>
              </div>

              {/* Quick Actions */}
              <div className="space-y-2">
                <p className="text-xs text-gray-500 dark:text-gray-400 mb-2 font-medium uppercase tracking-wider">快捷操作</p>
                <Button variant="outline" className="w-full justify-start" size="sm">
                  <Play className="w-3 h-3 mr-2" />
                  开始工作
                </Button>
                <Button variant="outline" className="w-full justify-start" size="sm">
                  <Clock className="w-3 h-3 mr-2" />
                  记录工时
                </Button>
                <Button variant="outline" className="w-full justify-start" size="sm">
                  <FileText className="w-3 h-3 mr-2" />
                  生成报告
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Right: Work Timeline */}
          <Card className="lg:col-span-2">
            <CardHeader>
              <CardTitle className="text-base flex items-center gap-2">
                <Clock className="w-4 h-4 text-blue-500" />
                工作记录
              </CardTitle>
            </CardHeader>
            <CardContent>
              {workLogs.length === 0 ? (
                <div className="text-center py-12">
                  <Clock className="w-12 h-12 text-gray-200 dark:text-gray-700 mx-auto mb-3" />
                  <p className="text-gray-400 dark:text-gray-500">暂无工作记录</p>
                  <p className="text-xs text-gray-300 dark:text-gray-600 mt-1">智能体开始工作后，记录将显示在这里</p>
                </div>
              ) : (
                <div className="relative">
                  {workLogs.map((log, idx) => (
                    <div key={log.id} className="flex gap-4 pb-6 relative">
                      {/* Timeline line */}
                      {idx < workLogs.length - 1 && (
                        <div className="absolute left-[7px] top-4 bottom-0 w-px bg-gray-200 dark:bg-gray-700" />
                      )}
                      {/* Timeline dot */}
                      <div
                        className={`w-4 h-4 rounded-full border-2 shrink-0 mt-0.5 z-10 ${
                          log.autoGenerated
                            ? 'bg-blue-500 border-blue-500'
                            : 'bg-emerald-500 border-emerald-500'
                        }`}
                      />
                      {/* Content */}
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-gray-900 dark:text-gray-100">
                          {log.description || '无描述'}
                        </p>
                        <div className="flex items-center gap-2 mt-1 text-xs text-gray-400 dark:text-gray-500">
                          <span>{log.date}</span>
                          {log.hours > 0 && <span>&middot; {log.hours}h</span>}
                          {log.autoGenerated && (
                            <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
                              自动
                            </Badge>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}
