// ============================================================
// Work Log Service - 智能体工作日志管理服务
// ============================================================

import type { ILogger, IEventBus } from '@/lib/core/types';

/**
 * 创建工作日志的数据
 */
export interface CreateWorkLogDTO {
  projectId: string;
  projectAgentId: string;
  taskId?: string;
  date: string;
  hours: number;
  description?: string;
  autoGenerated?: boolean;
}

/**
 * 更新工作日志的数据
 */
export interface UpdateWorkLogDTO {
  hours?: number;
  description?: string;
  date?: string;
}

/**
 * 工作日志列表查询参数
 */
export interface WorkLogListQuery {
  projectId: string;
  projectAgentId?: string;
  dateFrom?: string;
  dateTo?: string;
  page?: number;
  pageSize?: number;
}

/**
 * 工作日志汇总查询参数
 */
export interface WorkLogSummaryQuery {
  projectId: string;
  groupBy?: 'agent' | 'date' | 'task';
  dateFrom?: string;
  dateTo?: string;
}

/**
 * 工作量看板项
 */
export interface WorkloadBoardItem {
  projectAgentId: string;
  agentId: string;
  agentName: string;
  agentType: string;
  role: string;
  totalHours: number;
  thisWeekHours: number;
  isActive: boolean;
}

/**
 * 智能体工作日志管理服务
 * 提供工作日志的记录、查询、汇总和工作量看板功能
 */
export class WorkLogService {
  constructor(
    private prisma: any,
    private eventBus: IEventBus,
    private logger: ILogger,
  ) {}

  /**
   * 记录工作日志
   * @param data - 工作日志数据
   * @returns 新创建的工作日志
   */
  async log(data: CreateWorkLogDTO) {
    this.logger.info('[WorkLogService] Logging work', {
      projectId: data.projectId,
      hours: data.hours,
    });

    const log = await this.prisma.agentWorkLog.create({ data });

    this.eventBus.emit({
      type: 'project.agent.workLogged',
      payload: {
        projectId: data.projectId,
        agentId: data.projectAgentId,
        hours: data.hours,
        date: data.date,
      },
      timestamp: new Date(),
      source: 'project-hub',
    });

    return log;
  }

  /**
   * 更新工作日志
   * @param id - 工作日志 ID
   * @param data - 更新数据
   * @returns 更新后的工作日志
   */
  async update(id: string, data: UpdateWorkLogDTO) {
    this.logger.info('[WorkLogService] Updating work log', { id, data });

    return this.prisma.agentWorkLog.update({ where: { id }, data });
  }

  /**
   * 删除工作日志
   * @param id - 工作日志 ID
   */
  async delete(id: string) {
    this.logger.info('[WorkLogService] Deleting work log', { id });

    return this.prisma.agentWorkLog.delete({ where: { id } });
  }

  /**
   * 获取工作日志列表（分页）
   * @param query - 查询参数
   * @returns 分页的工作日志列表
   */
  async list(query: WorkLogListQuery) {
    this.logger.info('[WorkLogService] Listing work logs', { query });

    const { projectId, projectAgentId, dateFrom, dateTo, page = 1, pageSize = 20 } = query;
    const where: any = { projectId };
    if (projectAgentId) where.projectAgentId = projectAgentId;
    if (dateFrom || dateTo) {
      where.date = {};
      if (dateFrom) where.date.gte = dateFrom;
      if (dateTo) where.date.lte = dateTo;
    }

    const [items, total] = await Promise.all([
      this.prisma.agentWorkLog.findMany({
        where,
        include: { projectAgent: { include: { agent: true } } },
        orderBy: { date: 'desc' },
        skip: (page - 1) * pageSize,
        take: pageSize,
      }),
      this.prisma.agentWorkLog.count({ where }),
    ]);

    return { items, total, page, pageSize, totalPages: Math.ceil(total / pageSize) };
  }

  /**
   * 获取工作日志汇总
   * @param query - 汇总查询参数，支持按智能体、日期或任务分组
   * @returns 分组汇总结果
   */
  async summary(query: WorkLogSummaryQuery) {
    this.logger.info('[WorkLogService] Getting work log summary', { query });

    const { projectId, groupBy = 'agent', dateFrom, dateTo } = query;
    const where: any = { projectId };
    if (dateFrom || dateTo) {
      where.date = {};
      if (dateFrom) where.date.gte = dateFrom;
      if (dateTo) where.date.lte = dateTo;
    }

    const logs = await this.prisma.agentWorkLog.findMany({
      where,
      include: { projectAgent: { include: { agent: true } } },
    });

    // 按指定字段分组
    const grouped: Record<string, { label: string; totalHours: number; entryCount: number }> = {};
    for (const log of logs) {
      let key = '';
      let label = '';
      if (groupBy === 'agent') {
        key = log.projectAgentId;
        label = log.projectAgent?.agent?.name || 'Unknown';
      } else if (groupBy === 'date') {
        key = log.date;
        label = log.date;
      } else {
        key = log.taskId || 'unassigned';
        label = log.taskId || '未关联任务';
      }
      if (!grouped[key]) grouped[key] = { label, totalHours: 0, entryCount: 0 };
      grouped[key].totalHours += log.hours;
      grouped[key].entryCount += 1;
    }

    return Object.values(grouped).sort((a, b) => b.totalHours - a.totalHours);
  }

  /**
   * 获取工作量看板
   * @param query - 包含 projectId 的查询参数
   * @returns 各智能体的工作量统计
   */
  async workloadBoard(query: { projectId: string }): Promise<WorkloadBoardItem[]> {
    this.logger.info('[WorkLogService] Getting workload board', { projectId: query.projectId });

    const agents = await this.prisma.projectAgent.findMany({
      where: { projectId: query.projectId, isActive: true },
      include: { agent: true, workLogs: true },
    });

    return agents.map((pa: any) => {
      const totalHours = pa.workLogs.reduce((sum: number, log: any) => sum + log.hours, 0);
      const thisWeekHours = pa.workLogs
        .filter((log: any) => {
          const logDate = new Date(log.date);
          const now = new Date();
          const weekStart = new Date(now);
          weekStart.setDate(now.getDate() - now.getDay());
          weekStart.setHours(0, 0, 0, 0);
          return logDate >= weekStart;
        })
        .reduce((sum: number, log: any) => sum + log.hours, 0);

      return {
        projectAgentId: pa.id,
        agentId: pa.agentId,
        agentName: pa.agent.name,
        agentType: pa.agent.clientType,
        role: pa.role,
        totalHours: Math.round(totalHours * 10) / 10,
        thisWeekHours: Math.round(thisWeekHours * 10) / 10,
        isActive: pa.isActive,
      };
    });
  }
}
