'use client';

import { useState, useEffect, useCallback } from 'react';
import { trpc } from '@/lib/trpc/client';
import { useToast } from '@/components/ui/toast';

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface ProjectFocusViewProps {
  projectId: string;
  onBack: () => void;
  onOpenTaskDetail?: (taskId: string) => void;
}

interface Project {
  id: string;
  name: string;
  description?: string | null;
  status: string;
  phase: string;
  priority: string;
  progress: number;
  techStack?: string[] | string | null;
  createdAt: string;
  updatedAt: string;
  agents?: any[];
}

interface Milestone {
  id: string;
  title: string;
  status: string;
  dueDate?: string | null;
  completedAt?: string | null;
}

interface WorkLog {
  id: string;
  taskId?: string | null;
  date: string;
  hours: number;
  description: string;
  autoGenerated: boolean;
  createdAt: string;
}

interface AgentInfo {
  id: string;
  name: string;
  clientType: string;
  role: string;
  capabilities?: string | null;
  isActive: boolean;
  apiKey?: string;
}

interface WorkloadSummary {
  totalHours: number;
  totalEntries: number;
  byTask: Record<string, number>;
}

interface FocusData {
  project: Project;
  milestones: Milestone[];
  recentWorkLogs: WorkLog[];
  fullWorkLogs: WorkLog[];
  workloadSummary: WorkloadSummary;
  agentInfo: AgentInfo | null;
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

const STATUS_COLOR: Record<string, string> = {
  active: 'bg-green-500',
  completed: 'bg-blue-500',
  paused: 'bg-yellow-500',
  archived: 'bg-gray-400',
};

const PHASE_LABEL: Record<string, string> = {
  requirements: '需求',
  planning: '规划',
  architecture: '架构',
  implementation: '开发',
  testing: '测试',
  deployment: '部署',
  completed: '完成',
};

const PRIORITY_LABEL: Record<string, string> = {
  urgent: '紧急',
  high: '高',
  medium: '中',
  low: '低',
};

const MILESTONE_STATUS_LABEL: Record<string, string> = {
  completed: '已完成',
  in_progress: '进行中',
  pending: '待开始',
};

function relativeTime(dateStr: string): string {
  if (!dateStr) return '';
  const now = Date.now();
  const then = new Date(dateStr).getTime();
  const diffMs = now - then;
  const diffMin = Math.floor(diffMs / 60000);
  const diffHr = Math.floor(diffMs / 3600000);
  const diffDay = Math.floor(diffMs / 86400000);

  if (diffMin < 1) return '刚刚';
  if (diffMin < 60) return `${diffMin}分钟前`;
  if (diffHr < 24) return `${diffHr}小时前`;
  if (diffDay < 30) return `${diffDay}天前`;
  return new Date(dateStr).toLocaleDateString('zh-CN');
}

function daysSince(dateStr: string): number {
  if (!dateStr) return 0;
  const diff = Date.now() - new Date(dateStr).getTime();
  return Math.max(1, Math.ceil(diff / 86400000));
}

function parseCapabilities(raw: string | null | undefined): string[] {
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function getInitials(name: string): string {
  if (!name) return '?';
  return name
    .split(/[\s-_]+/)
    .slice(0, 2)
    .map((w) => w[0]?.toUpperCase() ?? '')
    .join('');
}

const AGENT_COLORS = [
  'bg-violet-500/20 text-violet-400',
  'bg-blue-500/20 text-blue-400',
  'bg-emerald-500/20 text-emerald-400',
  'bg-amber-500/20 text-amber-400',
  'bg-rose-500/20 text-rose-400',
];

function agentColor(index: number): string {
  return AGENT_COLORS[index % AGENT_COLORS.length];
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function ProjectFocusView({
  projectId,
  onBack,
  onOpenTaskDetail,
}: ProjectFocusViewProps) {
  const [focusData, setFocusData] = useState<FocusData | null>(null);
  const [tasks, setTasks] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [refreshKey, setRefreshKey] = useState(0);
  const [showAllLogs, setShowAllLogs] = useState(false);
  const { success, error: toastError } = useToast();

  /* ---- data fetching ---- */

  const fetchFocusData = useCallback(async () => {
    try {
      setIsLoading(true);
      const [data, tasksData] = await Promise.all([
        trpc.commandCenter.projectFocus.query({ projectId }),
        trpc.projectHub.tasks.list.query({ projectId }),
      ]);
      setFocusData(data as unknown as FocusData);
      setTasks(((tasksData as any)?.items ?? []) as any[]);
    } catch (err) {
      console.error('[FocusView] Failed:', err);
    } finally {
      setIsLoading(false);
    }
  }, [projectId]);

  useEffect(() => {
    fetchFocusData();
  }, [fetchFocusData, refreshKey]);

  /* ---- task status update ---- */

  const updateTaskStatus = async (taskId: string, newStatus: string) => {
    try {
      await trpc.projectHub.tasks.updateStatus.mutate({
        id: taskId,
        status: newStatus,
      });
      const statusLabel: Record<string, string> = {
        todo: '待办',
        in_progress: '进行中',
        done: '已完成',
      };
      success('任务已更新', `状态变更为「${statusLabel[newStatus] || newStatus}」`);
      setRefreshKey((k) => k + 1);
    } catch {
      toastError('状态更新失败', '任务状态变更时发生错误');
    }
  };

  /* ---- loading / empty ---- */

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-muted-foreground animate-pulse">加载项目详情...</div>
      </div>
    );
  }

  if (!focusData?.project) {
    return (
      <div className="flex flex-col items-center justify-center h-64 text-muted-foreground">
        <div className="text-4xl mb-2">😕</div>
        <div className="text-sm">项目未找到</div>
        <button
          onClick={onBack}
          className="mt-2 text-xs text-primary hover:underline"
        >
          返回全景
        </button>
      </div>
    );
  }

  /* ---- derived data ---- */

  const { project, milestones, recentWorkLogs, fullWorkLogs, workloadSummary, agentInfo } =
    focusData;

  const agent = agentInfo ?? project.agents?.[0] ?? null;
  const allWorkLogs = fullWorkLogs ?? recentWorkLogs ?? [];
  const displayLogs = showAllLogs ? allWorkLogs : allWorkLogs.slice(0, 20);

  const todoTasks = tasks.filter((t: any) => t.status === 'todo');
  const inProgressTasks = tasks.filter((t: any) => t.status === 'in_progress');
  const doneTasks = tasks.filter((t: any) => t.status === 'done');

  const totalTasks = tasks.length;
  const completedTasks = doneTasks.length;
  const completionRate = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

  const techStack: string[] = Array.isArray(project.techStack)
    ? project.techStack
    : typeof project.techStack === 'string'
      ? project.techStack.split(',').map((s) => s.trim()).filter(Boolean)
      : [];

  const capabilities = parseCapabilities(agent?.capabilities);

  const nextStatusMap: Record<string, { left: string | null; right: string }> = {
    todo: { left: null, right: 'in_progress' },
    in_progress: { left: 'todo', right: 'done' },
    done: { left: 'in_progress', right: null },
  };

  /* ---- sub-renderers ---- */

  const renderTaskCard = (task: any) => {
    const hours = workloadSummary?.byTask?.[task.id];
    const ns = nextStatusMap[task.status];

    return (
      <div
        key={task.id}
        onClick={() => onOpenTaskDetail?.(task.id)}
        className="group p-3 rounded-lg border bg-card hover:shadow-sm hover:border-primary/30 cursor-pointer transition-all"
      >
        <div className="flex items-start justify-between mb-1">
          <span className="text-sm font-medium leading-snug">{task.title}</span>
          <span
            className={`shrink-0 ml-2 text-[10px] px-1.5 py-0.5 rounded font-medium ${
              task.priority === 'high' || task.priority === 'urgent'
                ? 'bg-red-500/10 text-red-500'
                : task.priority === 'medium'
                  ? 'bg-yellow-500/10 text-yellow-500'
                  : 'bg-muted text-muted-foreground'
            }`}
          >
            {PRIORITY_LABEL[task.priority] ?? task.priority}
          </span>
        </div>

        {task.description && (
          <p className="text-xs text-muted-foreground line-clamp-2 mb-2">
            {task.description}
          </p>
        )}

        <div className="flex items-center justify-between">
          {hours != null ? (
            <span className="text-[10px] text-muted-foreground flex items-center gap-1">
              <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6l4 2" />
              </svg>
              {hours.toFixed(1)}h
            </span>
          ) : (
            <span />
          )}

          <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
            {ns?.left && (
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  updateTaskStatus(task.id, ns.left!);
                }}
                className="px-2 py-0.5 text-[10px] rounded bg-muted hover:bg-muted/80 transition-colors"
              >
                ← {ns.left === 'todo' ? '待办' : '进行中'}
              </button>
            )}
            {ns?.right && (
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  updateTaskStatus(task.id, ns.right);
                }}
                className="px-2 py-0.5 text-[10px] rounded bg-primary/10 text-primary hover:bg-primary/20 transition-colors"
              >
                {ns.right === 'done' ? '完成' : '开始'} →
              </button>
            )}
          </div>
        </div>
      </div>
    );
  };

  const renderTaskColumn = (columnTasks: any[], title: string, color: string) => (
    <div className="flex-1 min-w-[220px]">
      <div className="flex items-center gap-2 mb-3">
        <span className={`w-2 h-2 rounded-full ${color}`} />
        <span className="text-sm font-medium">{title}</span>
        <span className="text-xs text-muted-foreground">({columnTasks.length})</span>
      </div>
      <div className="space-y-2">
        {columnTasks.length === 0 ? (
          <div className="text-xs text-muted-foreground text-center py-6 border border-dashed rounded-lg">
            暂无任务
          </div>
        ) : (
          columnTasks.map(renderTaskCard)
        )}
      </div>
    </div>
  );

  /* ---- main render ---- */

  return (
    <div className="space-y-4">
      {/* ============================================================ */}
      {/*  Section 1: 项目概览                                          */}
      {/* ============================================================ */}
      <section className="p-5 rounded-xl border bg-card">
        {/* back + title row */}
        <div className="flex items-start gap-3 mb-3">
          <button
            onClick={onBack}
            className="mt-0.5 text-sm text-muted-foreground hover:text-foreground transition-colors shrink-0"
          >
            ← 返回
          </button>
          <div className="flex-1 min-w-0">
            <div className="flex flex-wrap items-center gap-2 mb-1">
              <span
                className={`w-2.5 h-2.5 rounded-full shrink-0 ${STATUS_COLOR[project.status] ?? 'bg-gray-400'}`}
              />
              <h2 className="text-xl font-bold truncate">{project.name}</h2>
              <span className="px-2 py-0.5 text-xs rounded-md bg-muted">
                {PHASE_LABEL[project.phase] ?? project.phase}
              </span>
              <span
                className={`text-xs px-2 py-0.5 rounded-md font-medium ${
                  project.priority === 'high' || project.priority === 'urgent'
                    ? 'bg-red-500/10 text-red-500'
                    : 'bg-muted text-muted-foreground'
                }`}
              >
                {PRIORITY_LABEL[project.priority] ?? project.priority}
              </span>
            </div>

            {project.description && (
              <p className="text-sm text-muted-foreground leading-relaxed">
                {project.description}
              </p>
            )}
          </div>
        </div>

        {/* progress bar */}
        <div className="flex items-center gap-3 mb-3">
          <div className="flex-1 max-w-md">
            <div className="h-2 bg-muted rounded-full overflow-hidden">
              <div
                className={`h-full rounded-full transition-all duration-500 ${
                  (project.progress ?? 0) >= 80
                    ? 'bg-green-500'
                    : (project.progress ?? 0) >= 40
                      ? 'bg-yellow-500'
                      : 'bg-primary'
                }`}
                style={{ width: `${project.progress ?? 0}%` }}
              />
            </div>
          </div>
          <span className="text-sm font-semibold tabular-nums">
            {project.progress ?? 0}%
          </span>
        </div>

        {/* tech stack + dates + agent pill */}
        <div className="flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
          {techStack.length > 0 && (
            <div className="flex items-center gap-1.5">
              {techStack.map((t) => (
                <span
                  key={t}
                  className="px-2 py-0.5 rounded-md bg-muted/60 text-foreground/70 text-[11px]"
                >
                  {t}
                </span>
              ))}
            </div>
          )}

          <span className="hidden sm:inline">·</span>

          <span>
            创建于 {new Date(project.createdAt).toLocaleDateString('zh-CN')}
          </span>

          <span>·</span>

          <span>
            更新于 {relativeTime(project.updatedAt)}
          </span>

          {agent && (
            <>
              <span className="hidden sm:inline">·</span>
              <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-muted/40 text-[11px]">
                <span
                  className={`w-1.5 h-1.5 rounded-full ${agent.isActive ? 'bg-green-500 animate-pulse' : 'bg-gray-400'}`}
                />
                🤖 {agent.name} · {agent.isActive ? '工作中' : '空闲'}
              </span>
            </>
          )}
        </div>
      </section>

      {/* ============================================================ */}
      {/*  Section 2: 智能体信息                                        */}
      {/* ============================================================ */}
      {agent && (
        <section className="p-4 rounded-xl border bg-card">
          <h3 className="text-sm font-semibold mb-3">🤖 智能体信息</h3>
          <div className="flex flex-col sm:flex-row gap-4">
            {/* left: avatar + identity */}
            <div className="flex items-center gap-3 sm:w-56 shrink-0">
              <div
                className={`w-10 h-10 rounded-full flex items-center justify-center text-sm font-bold ${agentColor(0)}`}
              >
                {getInitials(agent.name)}
              </div>
              <div className="min-w-0">
                <div className="text-sm font-medium truncate">{agent.name}</div>
                <div className="flex items-center gap-1.5 mt-0.5">
                  <span className="px-1.5 py-0.5 rounded bg-muted text-[10px] font-medium">
                    {agent.clientType}
                  </span>
                  <span className="text-[11px] text-muted-foreground">{agent.role}</span>
                </div>
              </div>
            </div>

            {/* middle: capabilities */}
            {capabilities.length > 0 && (
              <div className="flex-1 min-w-0">
                <div className="text-[11px] text-muted-foreground mb-1.5">能力标签</div>
                <div className="flex flex-wrap gap-1.5">
                  {capabilities.map((c) => (
                    <span
                      key={c}
                      className="px-2 py-0.5 rounded-md bg-primary/5 text-primary/70 text-[11px] border border-primary/10"
                    >
                      {c}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* right: workload summary */}
            <div className="sm:text-right shrink-0">
              <div className="text-[11px] text-muted-foreground mb-1">工时统计</div>
              <div className="flex sm:flex-col items-center sm:items-end gap-3 sm:gap-1">
                <div>
                  <span className="text-2xl font-bold tabular-nums">
                    {workloadSummary?.totalHours?.toFixed(1) ?? '0.0'}
                  </span>
                  <span className="text-xs text-muted-foreground ml-1">小时</span>
                </div>
                <div className="text-[11px] text-muted-foreground">
                  {workloadSummary?.totalEntries ?? 0} 条记录
                </div>
                <div
                  className={`inline-flex items-center gap-1 text-[11px] ${agent.isActive ? 'text-green-500' : 'text-muted-foreground'}`}
                >
                  <span
                    className={`w-1.5 h-1.5 rounded-full ${agent.isActive ? 'bg-green-500 animate-pulse' : 'bg-gray-400'}`}
                  />
                  {agent.isActive ? '在线工作中' : '当前空闲'}
                </div>
              </div>
            </div>
          </div>
        </section>
      )}

      {/* ============================================================ */}
      {/*  Section 3: 任务看板                                          */}
      {/* ============================================================ */}
      <section className="p-4 rounded-xl border bg-card">
        <h3 className="text-sm font-semibold mb-3">📋 任务看板</h3>
        <div className="flex gap-4 overflow-x-auto pb-2">
          {renderTaskColumn(todoTasks, '待办', 'bg-gray-400')}
          {renderTaskColumn(inProgressTasks, '进行中', 'bg-yellow-500')}
          {renderTaskColumn(doneTasks, '已完成', 'bg-green-500')}
        </div>
      </section>

      {/* ============================================================ */}
      {/*  Section 4: 工作日志时间线                                     */}
      {/* ============================================================ */}
      <section className="p-4 rounded-xl border bg-card">
        <h3 className="text-sm font-semibold mb-3">
          📝 工作日志
          <span className="ml-2 text-xs font-normal text-muted-foreground">
            ({allWorkLogs.length} 条记录)
          </span>
        </h3>

        {displayLogs.length === 0 ? (
          <div className="text-xs text-muted-foreground text-center py-8 border border-dashed rounded-lg">
            暂无工作日志
          </div>
        ) : (
          <div className="relative">
            {/* vertical line */}
            <div className="absolute left-[7px] top-2 bottom-2 w-px bg-border" />

            <div className="space-y-3">
              {displayLogs.map((log) => {
                const taskName =
                  log.taskId
                    ? tasks.find((t: any) => t.id === log.taskId)?.title
                    : null;

                return (
                  <div key={log.id} className="relative pl-7">
                    {/* dot */}
                    <span
                      className={`absolute left-0 top-1.5 w-[15px] h-[15px] rounded-full border-2 border-background flex items-center justify-center ${
                        log.autoGenerated
                          ? 'bg-blue-500 border-blue-500'
                          : 'bg-green-500 border-green-500'
                      }`}
                    >
                      <span className="w-1 h-1 rounded-full bg-background" />
                    </span>

                    {/* content */}
                    <div className="group">
                      <div className="flex flex-wrap items-center gap-2 mb-0.5">
                        <span className="text-[11px] text-muted-foreground">
                          {relativeTime(log.createdAt || log.date)}
                        </span>
                        <span className="px-1.5 py-0.5 rounded bg-muted text-[10px] font-medium tabular-nums">
                          {log.hours.toFixed(1)}h
                        </span>
                        <span
                          className={`text-[10px] px-1.5 py-0.5 rounded ${
                            log.autoGenerated
                              ? 'bg-blue-500/10 text-blue-500'
                              : 'bg-green-500/10 text-green-500'
                          }`}
                        >
                          {log.autoGenerated ? '自动' : '手动'}
                        </span>
                      </div>
                      <p className="text-sm leading-relaxed">{log.description}</p>
                      {taskName && (
                        <span className="inline-block mt-1 text-[11px] text-primary/70 hover:text-primary cursor-pointer transition-colors"
                          onClick={() => onOpenTaskDetail?.(log.taskId!)}
                        >
                          ↳ {taskName}
                        </span>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>

            {/* expand button */}
            {allWorkLogs.length > 20 && (
              <div className="mt-3 text-center">
                <button
                  onClick={() => setShowAllLogs((v) => !v)}
                  className="text-xs text-primary hover:underline transition-colors"
                >
                  {showAllLogs
                    ? '收起'
                    : `展开更多 (${allWorkLogs.length - 20} 条)`}
                </button>
              </div>
            )}
          </div>
        )}
      </section>

      {/* ============================================================ */}
      {/*  Section 5: 里程碑                                            */}
      {/* ============================================================ */}
      {milestones && milestones.length > 0 && (
        <section className="p-4 rounded-xl border bg-card">
          <h3 className="text-sm font-semibold mb-4">📅 里程碑</h3>

          {/* horizontal progress track */}
          <div className="relative overflow-x-auto pb-2">
            <div className="flex items-start gap-0 min-w-max">
              {milestones.map((ms, idx) => {
                const isCompleted = ms.status === 'completed';
                const isCurrent = ms.status === 'in_progress';
                const isLast = idx === milestones.length - 1;

                return (
                  <div key={ms.id} className="flex items-start">
                    {/* node */}
                    <div className="flex flex-col items-center w-28 shrink-0">
                      {/* circle */}
                      <div
                        className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold border-2 transition-all ${
                          isCompleted
                            ? 'bg-green-500 border-green-500 text-white'
                            : isCurrent
                              ? 'bg-blue-500 border-blue-500 text-white animate-pulse'
                              : 'bg-card border-muted-foreground/30 text-muted-foreground'
                        }`}
                      >
                        {isCompleted ? (
                          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                          </svg>
                        ) : (
                          idx + 1
                        )}
                      </div>

                      {/* label */}
                      <span
                        className={`mt-1.5 text-[11px] text-center leading-tight font-medium ${
                          isCompleted
                            ? 'text-green-500'
                            : isCurrent
                              ? 'text-blue-500'
                              : 'text-muted-foreground'
                        }`}
                      >
                        {ms.title}
                      </span>

                      {/* due date */}
                      {ms.dueDate && (
                        <span className="mt-0.5 text-[10px] text-muted-foreground">
                          {new Date(ms.dueDate).toLocaleDateString('zh-CN', {
                            month: 'short',
                            day: 'numeric',
                          })}
                        </span>
                      )}

                      {/* completed date */}
                      {ms.completedAt && (
                        <span className="mt-0.5 text-[10px] text-green-500/70">
                          ✓ {new Date(ms.completedAt).toLocaleDateString('zh-CN', {
                            month: 'short',
                            day: 'numeric',
                          })}
                        </span>
                      )}
                    </div>

                    {/* connector line */}
                    {!isLast && (
                      <div className="flex-1 h-0.5 mt-4 min-w-[40px] max-w-[60px]">
                        <div
                          className={`h-full rounded-full ${
                            isCompleted ? 'bg-green-500' : 'bg-muted-foreground/20'
                          }`}
                        />
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </section>
      )}

      {/* ============================================================ */}
      {/*  Section 6: 快速统计                                          */}
      {/* ============================================================ */}
      <section className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {/* 总工时 */}
        <div className="p-4 rounded-xl border bg-card text-center">
          <div className="text-[11px] text-muted-foreground mb-1">总工时</div>
          <div className="text-2xl font-bold tabular-nums">
            {workloadSummary?.totalHours?.toFixed(1) ?? '0.0'}
          </div>
          <div className="text-[10px] text-muted-foreground">小时</div>
        </div>

        {/* 任务完成率 */}
        <div className="p-4 rounded-xl border bg-card text-center">
          <div className="text-[11px] text-muted-foreground mb-1">任务完成率</div>
          <div className="text-2xl font-bold tabular-nums">{completionRate}%</div>
          <div className="text-[10px] text-muted-foreground">
            {completedTasks}/{totalTasks}
          </div>
        </div>

        {/* 工作记录 */}
        <div className="p-4 rounded-xl border bg-card text-center">
          <div className="text-[11px] text-muted-foreground mb-1">工作记录</div>
          <div className="text-2xl font-bold tabular-nums">
            {workloadSummary?.totalEntries ?? 0}
          </div>
          <div className="text-[10px] text-muted-foreground">条</div>
        </div>

        {/* 项目天数 */}
        <div className="p-4 rounded-xl border bg-card text-center">
          <div className="text-[11px] text-muted-foreground mb-1">项目天数</div>
          <div className="text-2xl font-bold tabular-nums">
            {daysSince(project.createdAt)}
          </div>
          <div className="text-[10px] text-muted-foreground">天</div>
        </div>
      </section>
    </div>
  );
}
